parserOptions:
  ecmaVersion: 2017
  sourceType: "module"
  ecmaFeatures:
    impliedStrict: true
rules:
  indent:
    - 2
    - 2
    - SwitchCase: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
env:
  es6: true
  node: true
  browser: true
  mocha: true
extends: 'eslint:recommended'
